### Length statistics

```{r utr_lengths_detected, results='asis', echo='FALSE'}
lengths <- results[['combined']]$length
lengths <- lengths[!is.na(lengths)]

coverage <- length(lengths) / nrow(results[['combined']])

output_template <- paste0("\n\n- %% %d'UTRs detected: **%0.2f**\n", 
                          "- Mean UTR length: **%0.2f**\n",
                          "- Median UTR length: **%0.2f**\n\n")

cat(sprintf(output_template, ifelse(feature_name == 'sl', 5, 3), 
            coverage, mean(lengths), median(lengths)))
```

```{r utr_length_stats}
quantile(lengths)
hist(lengths)
```

## Alternative site usage

```{r alt_site_usage_function}
#
# create_utr_comparison_df
#
create_utr_comparison_df <- function(stage1, stage2) {
    # input site usage dataframes
    df1 <- results[[stage1]]
    df2 <- results[[stage2]]

    comparison_df <- tbl_df(data.frame(
        name=df1$name,
        stage1_len=df1$length,
        stage2_len=df2$length,
        len_diff=abs(df1$length - df2$length),
        min_prim_nreads=pmin(df1$num_reads_primary, df2$num_reads_primary),
        min_ptos_ratio=pmin(df1$num_reads_primary / df1$num_reads_secondary, 
                            df2$num_reads_primary / df2$num_reads_secondary),
        count_min=pmin(df1$num_reads_primary, df2$num_reads_primary),
        stage1_stage2_ratio_stage1_samples=(df1$num_reads_primary /
                            pmax(results_cross_stage[[stage1]][[stage2]], 1)),
        stage2_stage1_ratio_stage2_samples=(df2$num_reads_primary / 
                            pmax(results_cross_stage[[stage2]][[stage1]], 1))
    ))

    # version with reads mapped for stages of interest
    comparison_df %>%
        filter(!is.na(stage1_len) & !is.na(stage2_len)) %>%
        mutate(
            log_min_ratio=log2(pmin(stage1_stage2_ratio_stage1_samples, stage2_stage1_ratio_stage2_samples)),
            length_diff=abs(stage1_len - stage2_len), 
            log_min_reads=log2(min_prim_nreads),
            log_min_ptos=log2(min_ptos_ratio),
            log_length_diff=log2(length_diff)
        )
}
```

```{r alt_site_usage, warning=FALSE, results='asis'}
# Generate stage comparison plots
comparisons_tested <- c()

for (s1 in stages) {
    for (s2 in stages) {
        # skip self-comparisons
        if (s1 == s2) {
            next
        }
        # if A vs. B has already been tested, skip B vs. A
        comparison_name <- paste0(sort(c(s1, s2)), collapse='')

        if(comparison_name %in% comparisons_tested) {
            next
        } else {
            comparisons_tested <- append(comparisons_tested, comparison_name)
        }

        # UTR comparison (s1 vs s2 / primary vs. secondary)
        utr_comparison_df <- create_utr_comparison_df(s1, s2) 

        plt <- ggplot(utr_comparison_df, 
            aes(stage1_len, stage2_len, color=log_min_ptos,
                size=min_prim_nreads)) + 
            geom_point() +
            xlab(s1) + ylab(s2) +
            scale_color_gradient2(low="black", mid="blue", high="red",
                                  limits=c(0,3)) +
            geom_abline(slope=1, intercept=300, color='#666666', lwd=0.5) +
            geom_abline(slope=1, intercept=-300, color='#666666', lwd=0.5) +
            scale_x_continuous(expand=c(0.01, 0.01)) +
            scale_y_continuous(expand=c(0.01, 0.01)) +
            geom_text(data=subset(utr_comparison_df, log_min_ptos >= 1.5 & min_prim_nreads >= 30 & len_diff > 10),
                      aes(stage1_len, stage2_len, label=name),
                      color='#000000', size=4, angle=45, hjust=0, vjust=0) +
            ggtitle(sprintf("%s site usage: %s vs. %s (All genes)", feature_name, s1, s2)) +
            theme(text=element_text(size=12, family='DejaVu Sans'),
                  plot.title=element_text(size=rel(1)))
            #coord_fixed()
            #geom_segment(aes(x=300, y=0, xend=6000, yend=5700, color='#666666'))
            #scale_colour_continuous(high='red') 
            #scale_size(trans='log')
        print(plt)

        # sites with switching only
        filtered_df <- utr_comparison_df %>% filter(stage1_len != stage2_len) 

        if (nrow(filtered_df) > 0) {
            # plot comparing primary vs. secondary site usage for each gene
            plt <- ggplot(filtered_df,
                aes(stage1_len, stage2_len, color=log_min_ptos,
                    size=log_min_reads)) + 
                geom_point() +
                xlab(s1) + ylab(s2) +
                scale_color_gradient2(low="black", mid="blue", high="red",
                                      limits=c(0,3)) +
                scale_size_continuous(limits=c(1,40)) +
                scale_size_continuous(limits=c(1,40)) +
                geom_abline(slope=1, intercept=300, color='#666666', lwd=0.5) +
                geom_abline(slope=1, intercept=-300, color='#666666', lwd=0.5) +
                scale_x_continuous(expand=c(0.01, 0.01)) +
                scale_y_continuous(expand=c(0.01, 0.01)) +
                geom_text(data=subset(utr_comparison_df, log_min_ptos >= 1.5 & log_min_reads >= 3 & len_diff > 10),
                          aes(stage1_len, stage2_len, label=name), size=4, angle=45, colour='#000000',
                              hjust=0, vjust=0) +
                ggtitle(sprintf("%s site usage: %s vs. %s (Genes with switching)", feature_name, s1, s2)) +
                theme(text=element_text(size=12, family='DejaVu Sans'),
                      plot.title=element_text(size=rel(1)))
                #coord_fixed()
            print(plt)

            # also save output as a table
            out_table <- file.path('..', outdir, sprintf("%s_%s_%s_vs_%s.csv",
                                                   outfile_prefix,
                                                   feature_name, s1, s2))
            write.csv(filtered_df, file=out_table, quote=FALSE)
        }

        # print genes with strongest site switching behavior
        stage1_stage2_utr_diff <- utr_comparison_df %>% 
            filter(count_min & log_min_ratio > 0.75) %>%
            select(-log_length_diff)

        cat(sprintf("\n\nNumber of alternatively %s genes (%s vs. %s): **%d**\n\n",
                      ifelse(feature_name == 'sl', 'trans-spliced',
                             'polyadenylated'), s1, s2,
                    nrow(stage1_stage2_utr_diff)))
    }
}
```
